package com.devmountain.noteApp.dtos;


import com.devmountain.noteApp.entities.Note;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class NoteDto implements Serializable {
    // The variables below that a note from the Notes table can have.
    // Note that the id is autogenerated, so we don't need to mess with it in the constructor below.
    private Long id;
    private String body;
    private UserDto userDto;

    // Constructor based on what the user inputted before - this is for when the User wants to grab an existing note, if I understood this correctly.
    public NoteDto(Note note) {
        if (note.getId() != null) {
            this.id = note.getId();
        }
        if (note.getBody() != null) {
            this.body = note.getBody();
        }
    }
}
